/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.model.User;
import hr.algebra.view.AdminPanel;
import hr.algebra.view.DownloadPanel;
import hr.algebra.view.EditActorsAndDirectorsPanel;
import hr.algebra.view.EditActorsPanel;
import hr.algebra.view.EditDirectorsPanel;
import hr.algebra.view.EditMoviesPanel;
import hr.algebra.view.LoginForm;

/**
 *
 * @author Patrik
 */
public class App extends javax.swing.JFrame {
    
    private static final String ADMIN = "Admin";
    private static final String EDIT_MOVIES = "Edit movies";
    private static final String EDIT_DIRECTORS = "Edit directors";
    private static final String EDIT_ACTORS= "Edit actors";
    private static final String EDIT_ACTORS_AND_DIRECTORS = "Edit actors and directors for movie";
    private static final String DOWNLOAD = "Download movies";
    
    private LoginForm loginForm;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        configurePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {
        loginForm = new LoginForm(this, true);
        loginForm.setVisible(true);
        User user = loginForm.getUser();
        if (user != null) {
            switch (user.getRole()) {
                    case "Administrator":
                        tpContent.add(ADMIN, new AdminPanel());
                        break;
                    case "User":
                        tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
                        tpContent.add(EDIT_DIRECTORS, new EditDirectorsPanel());
                        tpContent.add(EDIT_ACTORS, new EditActorsPanel());
                        tpContent.add(EDIT_ACTORS_AND_DIRECTORS, new EditActorsAndDirectorsPanel());
                        tpContent.add(DOWNLOAD, new DownloadPanel());
                        break;
                    default:
                        System.exit(0);
                        throw new AssertionError();
                }
        }
        else{
            System.exit(0);
            throw new AssertionError();
        }
    }
}
